# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a87e17a5c05e9dcac11b29d92e0ebba9664ca4d9f75659ae267b06d61ee64d8df5eab5a76b01456f5fd2ce0fe81a457aa2d7fc5e047a7629ed49cdfa8bef63a

test:
  secret_key_base: 9ce791327b51640a4e6b5785f8a864daf8138b64a0f54cd03625ba4d38660d3087625393211604797e88604a3a29d39a7ad4639544daf590fcf64fbc609235b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
